### ISSUE TITLE
Alternatives to Travis CI?

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#323]
Travis seems to fail to report build status to GitHub.That's annoying. Since support seems to be non-existent (and there are multiple reports about this problem existing), it might make sense to switch to something else / more reliable.

Edit: #317 and #324 also still show their Travis build as pending...

**Comment by psychon** [comment]
Seems like Travis CI is working on this: https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798/8

**Comment by psychon** [comment]
Travis fails to report build statuses again... :-(

**Comment by eduardosm** [comment]
What about Github Actions? Hopefully, Github won't fail to report to Github.

**Comment by psychon** [comment]
Yup, that would also be my first idea. Dunno about the mips runner, but in the worst case we could just drop that big endian test...

**Comment by psychon** [comment]
I gave GH actions a try and it more or less seems to work: https://github.com/psychon/x11rb/tree/github-workflow
Still want to make more checks before doing a PR (as in: "does this actually fail if something goes wrong?", e.g. cause a code gen change and see it fail, cause an endianess error and see it fail, ...)

Also: I have no clue about what I am doing here

**Comment by eduardosm** [comment]
Beware with `cargo test --all-targets` (https://github.com/rust-lang/cargo/issues/6669). You can omit `--all-targets` (or use `--all` if you want to test all crates in the workspace).

https://github.com/psychon/x11rb/blob/d4e29a3795e1a4eec70b84d9ea7ac4580dddf65a/.github/workflows/CI.yml#L83

**Comment by psychon** [comment]
Okay, will replace `--all-targets` with `--workspace` (per `cargo test --help`):
```
        --all                        Alias for --workspace (deprecated)
        --workspace                  Test all packages in the workspace
```
Will also add a new badge to the README.

**Comment by psychon** [comment]
Argh. `--all` also does not work with Rust 1.37:
```
error[E0658]: use of unstable library feature 'checked_duration_since'
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parking-2.0.0/src/lib.rs:144:32
    |
144 |             .park(Some(instant.saturating_duration_since(Instant::now())))
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/58402

error: aborting due to previous error
```
I feel like "back to the drawing bord". The Rust 1.37 job needs so much special treatment that it should be separated into its own job.

What exactly do we want for Rust 1.37? Is running `cargo check` just for the "main crate" (x11rb) enough? Could there be errors that would not be caught by that?

**Comment by eduardosm** [comment]
> What exactly do we want for Rust 1.37? Is running `cargo check` just for the "main crate" (x11rb) enough? Could there be errors that would not be caught by that?

Yeah, a `cargo check` on x11rb enabling as many features as possible should be enough.

Anyways, is it worth keeping 1.37 compatibility?

**Comment by psychon** [comment]
> Anyways, is it worth keeping 1.37 compatibility?

What would you do instead?

Replacing 1.37 with a newer version? If so, which one and why?

Only being compatible with latest Rust master? While that seems common in the Rust ecosystem, I feel like that can cause too much churn for others for little gain.
Perhaps I have just been doing too much C and "you have to upgrade your compiler" is common these days...

**Comment by eduardosm** [comment]
Maybe 1.40 is a good choice:
* It can build all crates in the workspace with all features
* It has `--workspace` (not much an advantage because `--all` is still fine)
* We can get rid of `I_need_rust_1_37_compatibility_but_know_that_enums_are_still_non_exhaustive`
* Staying away from rustup, it is available in [Debian 9](https://packages.debian.org/stretch/rustc), [Ubuntu 16.04 LTS](https://packages.ubuntu.com/xenial/rustc) and [Fedora 32](https://dl.fedoraproject.org/pub/fedora/linux/releases/32/Everything/x86_64/os/Packages/r/).

However, we still wouldn't get rid of clippy issues

**Comment by eduardosm** [comment]
I can continue working on this if you don't have time.

**Comment by psychon** [comment]
Feel free to do so. I'd hope that you come up with improvements and the total result is more readable / less messy.

Time-wise... my travel plans were Corona'd and so I will not be AFK as originally planned.
