### PR TITLE
Add dl-libxcb feature

### PR DESCRIPTION
**Pull request by eduardosm**
Enabling this feature will prevent from libxcb being linked to the resulting executable. Instead libxcb will be dynamically loaded at runtime.

This allows to compile an application with different graphic backends that may run with another backend if libxcb is not installed on the system.

Fixes https://github.com/psychon/x11rb/issues/522.

### CODE REVIEW

File: src/xcb_ffi/raw_ffi.rs [hunk 1]
```diff
@@ -129,57 +132,182 @@ pub(crate) mod send_request_flags {
...
+    _library: libloading::Library,
+    funcs: LibxcbFuncs,
+}
+
+#[cfg(all(not(test), feature = "dl-libxcb"))]
+impl LibxcbLibrary {
+    fn open_lib() -> Result<libloading::Library, LibxcbLoadError> {
+        // TODO: Names for non-unix platforms
+        #[cfg(unix)]
+        const LIB_NAMES: &[&str] = &["libxcb.so.1", "libxcb.so"];
```
Comment (psychon) [inline src/xcb_ffi/raw_ffi.rs:147]: Why both the full SONAME and also the short version? Shouldn't either be enough?

(I'd say `libxcb.so.1` is the way to go, but I am not entirely sure...)

File: src/xcb_ffi/raw_ffi.rs [hunk 2]
```diff
@@ -129,57 +132,182 @@ pub(crate) mod send_request_flags {
...
+        compile_error!("dl-libxcb feature is not supported on non-unix");
+
+        let mut errors = Vec::new();
+        for lib_name in LIB_NAMES.iter() {
+            match libloading::Library::new(lib_name) {
+                Ok(library) => return Ok(library),
+                Err(e) => errors.push((lib_name.into(), e.to_string())),
+            }
+        }
+        Err(LibxcbLoadError::OpenLibError(errors))
```
Comment (psychon) [inline src/xcb_ffi/raw_ffi.rs:158]: If this only tried `libxcb.so.1`, the error handling could also be simplified and the `Vec` of errors would become unnecessary...

File: src/xcb_ffi/raw_ffi.rs [hunk 3]
```diff
@@ -129,57 +132,182 @@ pub(crate) mod send_request_flags {
...
+        let funcs = LibxcbFuncs::new(&library)
+            .map_err(|(symbol, e)| LibxcbLoadError::GetSymbolError(symbol.into(), e.to_string()))?;
+        Ok(Self {
+            _library: library,
+            funcs,
+        })
+    }
+}
+
+#[cfg(all(not(test), feature = "dl-libxcb"))]
```
Comment (psychon) [inline src/xcb_ffi/raw_ffi.rs:178]: How about moving things into an extra module so that only one instance of this repeated `#[cfg]` is necessary?

File: src/xcb_ffi/raw_ffi.rs [hunk 4]
```diff
@@ -129,57 +132,182 @@ pub(crate) mod send_request_flags {
...
+use once_cell::sync::Lazy;
+
+#[cfg(all(not(test), feature = "dl-libxcb"))]
+static LIBXCB_LIBRARY: Lazy<Result<LibxcbLibrary, LibxcbLoadError>> =
+    Lazy::new(|| unsafe { LibxcbLibrary::load() });
+
+#[cfg(all(not(test), feature = "dl-libxcb"))]
+fn get_libxcb() -> &'static LibxcbLibrary {
+    #[cold]
+    #[inline(never)]
```
Comment (psychon) [inline src/xcb_ffi/raw_ffi.rs:188]: Why...?

**Review by psychon — APPROVED** [review]
Basically: I trust you, so :+1:

File: src/xcb_ffi/raw_ffi.rs (hunk 1 above)
Comment (eduardosm) [reply src/xcb_ffi/raw_ffi.rs:147]: Indeed, if we ever have a "libxcb.so.2" and a "libxcb.so" that links to it, we should not try to use it because there is presumably ABI/API breakage, so I'll change it to a single name.

File: src/xcb_ffi/raw_ffi.rs (hunk 3 above)
Comment (eduardosm) [reply src/xcb_ffi/raw_ffi.rs:178]: Not a bad idea.

File: src/xcb_ffi/raw_ffi.rs (hunk 4 above)
Comment (eduardosm) [reply src/xcb_ffi/raw_ffi.rs]: To try to reduce code size, `get_libxcb` is called in every xcb function wrapper:

https://github.com/psychon/x11rb/blob/b0b0332433ddabf2a8edd42169816d555a4177fc/src/xcb_ffi/raw_ffi.rs#L245-L251

So this tries to keep the error handling code "out of the way".

Something similar is done in the standard library:

https://github.com/rust-lang/rust/blob/4529af972e55f8f85afaada0ee2dd18ab8653637/library/core/src/option.rs#L343-L348
https://github.com/rust-lang/rust/blob/4529af972e55f8f85afaada0ee2dd18ab8653637/library/core/src/option.rs#L1222-L1227

**Comment by psychon** [comment]
Just for future me when I want to see why libloading does not work on 1.37:
```
error[E0658]: non exhaustive is an experimental feature
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.6.3/src/error.rs:23:1
   |
23 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/44109
```
